### ISSUE TITLE
Should we add a README?

### ISSUE THREAD

**Issue by Lazerbeak12345** [DrEthan77/Ethannet#1]
I am quite familiar with markdown :tada:, and I could do that for you, granted it may not be needed. __What do you think?__

**Comment by Lazerbeak12345** [comment]
Other things we may want to add:

* a CONTRIBUTING file
* a LICENCE file

And it may help you to see [this GitHub page](https://github.com/DrEthan77/Ethannet/community) that details how to make it compatible with the community.

**Comment by DrEthan77** [comment]
you could add those :D

**Comment by DrEthan77** [comment]
ok done it isnt much doe
